pub enum COMMAND {
    EXIT,
    HELP,
    NICK (String),
    USER {username: String, realname: String},
    SERVER (String),
    JOIN (String),
    PART (String),
    PRIVMSG {target: String, message: String},
    NOTICE {target: String, message: String},
    QUIT (String),
    MODE {target: String, mode: String},
    TOPIC {channel: String, topic: String},
    WHO (String),
    WHOIS (String), 
    LIST, 
    KICK {channel: String, user: String, reason: String}, 
    INVITE {nick: String, channel: String},
}